spring:
  datasource:
    url: jdbc:mysql://sodam-dadam-database.czcfkoivbrbz.ap-northeast-2.rds.amazonaws.com:3306/sodam_dadam
    username: root
    password: a6450307!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 1800000

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: 3.39.120.178 # 로컬에서 테스트 할 때는 localhost로 사용
      port: 6379
      password: a6450307


#logging.level:
#  org.hibernate.SQL: debug
